"$schema" = "node_modules/wrangler/config-schema.json"
name = "unreal"
# main = "src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[observability]
enabled = true


# Define environment variables
[vars]

#origin = "http://localhost:8787"
