name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  envfile: ${{secrets.ENV}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: ">=1"
          bun-repo: "oven-sh/bun"
          cache: true

      - name: Install Dependencies
        run: |
          cp .env.example .env
          bun install

      - name: Write environment
        run: |
          echo "$envfile" >> .env

      - name: Build
        run: |
          bun run cloudflare:build

      - name: Deploy to Cloudflare
        run: |
          bun run cloudflare:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
